version: '3.1'
services:

  nomis-oauth2-server:
    image: mojdigitalstudio/nomis-oauth2-server:latest
    container_name: nomis-oauth2-server
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    deploy:
        replicas: 1
        update_config:
          parallelism: 1
          delay: 10s
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == worker]
    environment:
      - JAVA_OPTS=-Xms256m -Xmx256m
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

