---
# Per environment values which override defaults in hmpps-auth/values.yaml
generic-service:
  replicaCount: 2

  ingress:
    host: sign-in-dev.hmpps.service.justice.gov.uk
    modsecurity_audit_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      SecRuleRemoveById 920320
      SecRuleRemoveById 920300
      SecRuleRemoveById 920440
      SecRuleRemoveById 942110
      SecRuleRemoveById 913101
      SecRuleUpdateTargetById 931130 "!ARGS:/redirect_uri/"
      SecRuleUpdateTargetById 942440 "!REQUEST_COOKIES:/jwtSession/"
      SecRuleUpdateTargetById 942450 "!REQUEST_COOKIES:/jwtSession/"
      SecRuleUpdateTargetById 930120 "!REQUEST_COOKIES:/jwtSession/"
      SecRuleUpdateTargetById 942210 "!REQUEST_COOKIES:/jwtSession/"
      SecRuleUpdateTargetById 942450 "!REQUEST_COOKIES:/savedrequest/"
      SecRuleUpdateTargetById 942200 "!ARGS:/query/"
      SecRuleUpdateTargetById 942430 "!ARGS:/query/"
      SecRuleUpdateTargetById 942480 "!ARGS:/query/"
      SecRuleUpdateTargetById 942450 "!ARGS:/state/"
      SecRuleUpdateTargetById 931130 "!ARGS:/registeredRedirectUriWithNewlines/"
      SecRuleUpdateTargetById 942430 "!ARGS:/registeredRedirectUriWithNewlines/"
      SecRuleUpdateTargetById 931130 "!ARGS:/url/"
      SecRuleUpdateTargetById 942440 "!ARGS:/refresh_token/"
      SecRuleUpdateTargetById 942430 "!ARGS:/code/"
      SecRuleUpdateTargetById 942440 "!ARGS:/code/"
      SecRuleUpdateTargetById 942260 "!ARGS:/newPassword/"
      SecRuleUpdateTargetById 942340 "!ARGS:/newPassword/"
      SecRuleUpdateTargetById 942260 "!ARGS:/confirmPassword/"
      SecRuleUpdateTargetById 942340 "!ARGS:/confirmPassword/"
      SecRuleUpdateTargetById 942130 "!ARGS:/clientSecret/"
      SecRuleUpdateTargetById 920230 "!ARGS:/password/"
      SecRuleUpdateTargetById 942130 "!ARGS:/password/"
      SecRuleUpdateTargetById 942440 "!ARGS:/password/"
      SecRuleUpdateTargetById 942450 "!ARGS:/password/"
      SecRuleUpdateTargetById 942190 "!ARGS:/password/"
      SecRuleUpdateTargetById 942330 "!ARGS:/password/"
      SecRuleUpdateTargetById 942440 "!REQUEST_COOKIES:/returnTo/"
      SecRuleUpdateTargetById 942450 "!REQUEST_COOKIES:/returnTo/"
      SecRuleUpdateTargetById 930120 "!REQUEST_COOKIES:/returnTo/"
      SecRuleUpdateTargetById 942210 "!REQUEST_COOKIES:/returnTo/"
      SecRuleUpdateTargetById 942120 "!ARGS:/client_secret/"
      SecRuleUpdateTargetById 942300 "!ARGS:/client_secret/"
      SecRuleUpdateTargetById 942430 "!ARGS:/client_secret/"
      SecRuleUpdateTargetById 941340 "!ARGS:/client_secret/"
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE"

  env:
    SPRING_PROFILES_ACTIVE: "nomis,delius,token-verification,azure-oidc,postgres"
    APPLICATION_SIGNIN_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/"
    APPLICATION_SUPPORT_URL: "https://support-dev.hmpps.service.justice.gov.uk/feedback-and-support"
    APPLICATION_AUTHENTICATION_MATCH_SUBDOMAINS: "true"
    APPLICATION_LINK_ACCOUNTS: "false"
    APPLICATION_NON_PROD_WARNING_ENABLED: "true"
    APPLICATION_NON_PROD_WARNING_PROD_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth/"
    APPLICATION_AUTHENTICATION_NOTIFY_PRE_DISABLE_ENABLED: "true"
    DELIUS_ENDPOINT_URL: "https://community-api-secure.test.delius.probation.hmpps.dsd.io"
    NOMIS_ENDPOINT_URL: "https://nomis-user-dev.aks-dev-1.studio-hosting.service.justice.gov.uk"
    JWT_JWK_KEY_ID: "dev-jwk-kid"
    TOKENVERIFICATION_ENDPOINT_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

  env_comma_joined_from_list:
    APPLICATION_AUTHENTICATION_MFA_ALLOWLIST:
      office: "217.33.148.210/32"
      mojvpn: "81.134.202.29/32"
      global_protect_vpn: "35.176.93.186/32"

# CloudPlatform AlertManager receiver to route Prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
