spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        show_sql: false
  profiles:
    include: ai

auth:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      show_sql: false
