server:
  port: 8901
  context-path: /auth

security:
  oauth2:
    client:
      client-id: keyworker
      client-secret: keyworkersecret
      scope: read,write
      auto-approve-scopes: '.*'

  user:
    password: password

logging:
  level:
    org.springframework.security: DEBUG