server:
  servlet:
    context-path: /auth
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto

spring:
  datasource:
    url: 'jdbc:h2:mem:testdb;Mode=Oracle'
    type: com.zaxxer.hikari.HikariDataSource

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

logging.level.uk.gov: INFO
management:
  endpoints:
    web:
      base-path: /
