version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.14
  browser-tools: circleci/browser-tools@1.2.4

parameters:
  alerts-slack-channel:
    type: string
    default: hmpps_tech_alerts_security

jobs:
  validate:
    executor:
      name: hmpps/java
      tag: "17.0"
    environment:
      _JAVA_OPTIONS: -Xmx800m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false

    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle.kts

  integration_tests:
    executor:
      name: hmpps/java
      tag: 17.0-browsers
    parallelism: 4
    environment:
      _JAVA_OPTIONS: -Xmx512m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - browser-tools/install-browser-tools
      - run:
          name: Run the java app.
          command: env spring.profiles.active=dev,token-verification,delius,nomis,azure-oidc-int-test java -Xmx256m -jar build/libs/hmpps-auth-*.jar
          background: true
      - run:
          name: Wait for java app to start
          command: sleep 20
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Configure test name globbing
          command: |
            circleci tests glob "**/integration/**/*.kt" | circleci tests split | xargs -n 1 echo
      - run:
          name: Run Fluent Integration Tests
          command: ./gradlew testIntegration -PciTestFilter="`circleci tests glob "**/integration/**/*.kt" | circleci tests split`"
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - /home/circleci/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle.kts" }}
          paths:
            - /home/circleci/.gradle/caches
      - store_artifacts:
          path: build/reports/tests/testIntegration
          destination: integration/fluent
      - store_test_results:
          path: build/test-results

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - integration_tests:
          requires:
            - validate
      - hmpps/helm_lint:
          name: helm_lint
          env: "devcp"
          helm_dir: "helm_deploy_cp"
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev_cp
          env: "devcp"
          jira_update: true
          helm_dir: "helm_deploy_cp"
          filters:
            branches:
              only:
                - main
          context:
            - hmpps-common-vars
            - hmpps-auth-devcp
          requires:
            - build_docker
            - helm_lint
            - integration_tests

      - request-stage-approval:
          type: approval
          requires:
            - deploy_dev_cp
      - hmpps/deploy_env:
          name: deploy_stage
          env: "stage"
          jira_update: true
          jira_env_type: testing
          helm_dir: "helm_deploy_cp"
          context:
            - hmpps-common-vars
            - hmpps-auth-stage
          requires:
            - request-stage-approval

      - request-preprod-approval:
          type: approval
          requires:
            - deploy_stage
      - hmpps/deploy_env:
          name: deploy_preprod_cp
          env: "preprodcp"
          jira_update: true
          jira_env_type: staging
          helm_dir: "helm_deploy_cp"
          context:
            - hmpps-common-vars
            - hmpps-auth-preprodcp
          requires:
            - request-preprod-approval

      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod_cp
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          jira_update: true
          jira_env_type: production
          slack_notification: true
          context:
            - hmpps-common-vars
            - hmpps-auth-prod
          requires:
            - request-prod-approval

      - hmpps/deploy_env:
          name: deploy_prodcp
          env: "prodcp"
          # jira_update: true
          # jira_env_type: production
          # slack_notification: true
          helm_dir: "helm_deploy_cp"
          context:
            - hmpps-common-vars
            - hmpps-auth-prodcp
          requires:
            - deploy_prod

  security:
    triggers:
      - schedule:
          cron: "43 5 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
            - veracode-credentials
  security-weekly:
    triggers:
      - schedule:
          cron: "0 6 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars


