---
# Per environment values which override defaults in hmpps-auth/values.yaml
generic-service:
  replicaCount: 8

  ingress:
    host: sign-in.hmpps.service.justice.gov.uk

  env:
    SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: 30
    SPRING_PROFILES_ACTIVE: "nomis,delius,token-verification,azure-oidc"
    APPLICATION_SIGNIN_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth/"
    APPLICATION_SUPPORT_URL: "https://support.hmpps.service.justice.gov.uk/feedback-and-support"
    APPLICATION_AUTHENTICATION_MATCH_SUBDOMAINS: "false"
    APPLICATION_LINK_ACCOUNTS: "false"
    APPLICATION_NON_PROD_WARNING_ENABLED: "false"
    APPLICATION_NON_PROD_WARNING_PROD_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth/"
    APPLICATION_AUTHENTICATION_NOTIFY_PRE_DISABLE_ENABLED: "true"
    DELIUS_ENDPOINT_URL: "https://community-api-secure.probation.service.justice.gov.uk"
    NOMIS_ENDPOINT_URL: "https://nomis-user.aks-live-1.studio-hosting.service.justice.gov.uk"
    JWT_JWK_KEY_ID: "prod-jwk-kid"
    TOKENVERIFICATION_ENDPOINT_URL: "http://token-verification-api.token-verification-api-prod.svc.cluster.local"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route Prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
  rdsAlertsDatabases:
    cloud-platform-edf050d943534f60: 'hmpps auth'
  rdsAlertsConnectionThreshold: 720
